let g:coc_global_extensions = [
  \ "coc-eslint",
  \ "coc-explorer",
  \ "coc-floatinput",
  \ "coc-json",
  \ "coc-html",
  \ "coc-yaml",
  \ "coc-python",
  \ "coc-java",
  \ "coc-prettier",
  \ "coc-rust-analyzer",
  \ "coc-toml",
  \ "coc-tsserver",
  \ "coc-marketplace",
  \ ]
