#!/bin/bash

SCRIPT_FOLDER="$HOME/.bin"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [ -f "$SCRIPT_FILE" ]; then
    echo file already exists
    $EDITOR "$SCRIPT_FILE"
    exit 1
fi

echo '#!/bin/bash' > "$SCRIPT_FILE"
figlet "$1" | awk '{print "# " $0}' >> "$SCRIPT_FILE"
echo "##" >> "$SCRIPT_FILE"

chmod a+x "$SCRIPT_FILE"
$EDITOR "$SCRIPT_FILE"

