#!/bin/bash
#                       
#   ___ ___  __ _  ___  
#  / __/ __|/ _` |/ _ \ 
# | (__\__ \ (_| | (_) |
#  \___|___/\__, |\___/ 
#           |___/       
##
# - fetches CS:GO stats

channel=0jdxt
steam_user=jxy__

function api {
    [ -n "$1" ] && url=$(printf "https://csgo-stats.net/api/nightbot/%s/%s/%s" "$1" "$channel" "$steam_user")
    curl "$url" 2>/dev/null | awk -F- '{print $1}'
}

case $1 in
    stats | inventory | rank)  api "$1";;
    *) echo "Usage: csgo <stats|inventory|rank>";;
esac

