#!/bin/sh
# The famous "get a menu of emojis to copy" script.

# get chosen emoji or exit
chosen=$(cut -d';' -f1 ~/uoou-bin/emoji_list | dmenu -z 1000 -i -g 3 -l 20 -p "Select a character:" | sed 's/ .*//')
[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
    # with arg, type
    xdotool type "$chosen"
else
    # without, copy
    echo "$chosen" | xclip -selection clipboard
    toastify send --id 98765 --icon gtk-copy "$chosen"
fi

