#!/usr/bin/bash
# shellcheck disable=SC2059

# The famous "get a menu of emojis to copy" script.

# get chosen emoji or exit
chosen=$(cut -d';' -f1 ~/.bin/emoji | dmenu -z 600 -i -g 3 -l 20 -p "Select a character:" | sed 's/ .*//')
[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
    # with arg, type
    xdotool type "$chosen"
else
    # without, copy
    printf "$chosen" | xclip -selection clipboard
    toastify send --id 98765 --icon gtk-copy "$chosen"
fi

