#!/bin/sh
# dmenu_run improved
# if a command ends with "!", it is started in term.

cmd="$(dmenu_path | dmenu "$@")"
case $cmd in
    *\! ) alacritty -e "$(echo "$cmd" | cut -d'!' -f1)";;
    * ) $cmd ;;
esac

