#!/bin/bash
#      _       _       _                   
#   __| | ___ | |_ ___| |_ _ __ __ _ _ __  
#  / _` |/ _ \| __/ __| __| '__/ _` | '_ \ 
# | (_| | (_) | |_\__ \ |_| | | (_| | |_) |
#  \__,_|\___/ \__|___/\__|_|  \__,_| .__/ 
#                                   |_|    
##

set -Eeo

cd ~

source .zshenv

if [ ! -f pkglist.txt ]; then
    echo "pkglist.txt not found"
    exit 1
fi

# install yay, to enable installing AUR packages as well as official ones
sudo pacman -Sy --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ~
rm -rf yay

# install packages
sudo pacman -S --needed - < pkglist.txt

sudo chsh $(which zsh)

# TODO:
# - cargo/rustup
# - topgrade

