#!/bin/bash
#
#   __ _  __ _ _ __ ___   ___  ___ _ __
#  / _` |/ _` | '_ ` _ \ / _ \/ __| '_ \
# | (_| | (_| | | | | | |  __/ (__| |_) |
#  \__, |\__,_|_| |_| |_|\___|\___| .__/
#  |___/                          |_|
##


[ -z "$1" ] && echo -e "Usage: gamecp \"search term\"\nTo execute the copy do: eval \$(gamecp \"term\")" && exit 1

linux="$HOME/.local/share/Steam/steamapps"
windows="/mnt/windows/Program Files (x86)/Steam/steamapps"
hdd="/mnt/windows/games/SteamLibrary/steamapps"

function copy {
    name=$(grep "installdir" "$manifest" | awk -F\" '{ print $4 }')
    dir="$found/common/$name"

    echo "Found $name in $found" >&2

    if [ -f "$linux/$(basename "$manifest")" ]; then
        echo "Warning: manifest exists"
        [ -d "$linux/common/$name" ] && echo "Warning: game directory exists"
        echo "Aborted copy"
        return 1
    fi

    echo "cp -r $dir $linux/common/"
    echo "cp $manifest $linux/"
}

sudo umount /dev/sda3 2>/dev/null
sudo umount /dev/sdb3 2>/dev/null

sudo mount /dev/sda3 /mnt/windows/ -o ro
if manifest=$(grep -lir "$1" "$windows/"*.acf); then
    found="$windows"
    copy
    ex=$?
    sudo umount /dev/sda3/
else
    sudo umount /dev/sda3/
    sudo mount /dev/sdb3 /mnt/windows/ -o ro
    if manifest=$(grep -lir "$1" "$hdd/"*.acf); then
        found="$hdd"
        copy
        ex=$?
        sudo umount /dev/sdb3/
    else
        echo "game not found"
        exit 1
    fi
fi

exit $ex
