#!/bin/sh
#                  _ _ _                 _
#  _ __ ___   __ _(_) | |__   ___   ___ | | __
# | '_ ` _ \ / _` | | | '_ \ / _ \ / _ \| |/ /
# | | | | | | (_| | | | | | | (_) | (_) |   <
# |_| |_| |_|\__,_|_|_|_| |_|\___/ \___/|_|\_\
#
##

new=$(notmuch new | tail -n1 | cut -d' ' -f2)
if [ "$new" != "new" ]; then
    unread=$(notmuch count tag:unread folder:INBOX)
    notify-send -i email notmuch "you have $new new mail\n($unread unread)"
fi

