#!/bin/bash
#                     _ _            _   _
#  _ __ ___   ___  __| (_) __ _  ___| |_| |
# | '_ ` _ \ / _ \/ _` | |/ _` |/ __| __| |
# | | | | | |  __/ (_| | | (_| | (__| |_| |
# |_| |_| |_|\___|\__,_|_|\__,_|\___|\__|_|
#
##


case $1 in
    t|f|b|p|n) ;;
    s)
        playerctld shift
        toastify send --id 8345 "mediactl" "$(playerctl -l | head -n1)"
        exit;;
    *)
        echo "Usage: mediactl t|f|b|p|n|s  (toggle, forward, back, prev, next, shift)"
        exit 1;;
esac

current="$(playerctl -l | head -n1)"
if [ "$current" = spotifyd ]; then
    case $1 in
        t) spt pb -t;;
        f) spt pb --seek +10;;
        b) spt pb --seek -10;;
        p) spt pb -p;;
        n) spt pb -n;;
    esac
else
    case $1 in
        t) playerctl play-pause;;
        f) playerctl position 10+;;
        b) playerctl position 10-;;
        p) playerctl previous;;
        n) playerctl next;;
    esac
fi

