#!/bin/bash
#        _             _ _     _
#  _ __ | | __ _ _   _| (_)___| |_
# | '_ \| |/ _` | | | | | / __| __|
# | |_) | | (_| | |_| | | \__ \ |_
# | .__/|_|\__,_|\__, |_|_|___/\__|
# |_|            |___/
##

latest=$(sfeed_plain .sfeed/feeds/VISION\ Radio | head -n1 | cut -d' ' -f12-)
name=$(echo "$latest" | cut -d' ' -f-3)
link=$(echo "$latest" | rev | cut -d' ' -f1 | rev)

echo "$name, $link"
# page=$(curl -SL "$link")

