#!/bin/bash

FILE=/tmp/polybarupdates

# helper to count lines of a command's output
function lc {
    "$@" 2>/dev/null | wc -l
}

# count updates
function fetch_updates {
    updates_arch=$(lc checkupdates)
    updates_aur=$(lc paru -Qum --devel)
    echo "📦 $(( updates_arch + updates_aur ))" > $FILE
}

spinner=(⡀ ⡄ ⡔ ⡜ ⠝ ⠛ ⠫ ⢣ ⢢ ⢠ ⢀ "⠀" "⠀" "⠀")
while true; do
    for c in "${spinner[@]}"; do
        echo "📦 $c"
        sleep 0.1
    done
done &
loop=$!

fetch_updates &
fetch=$!

wait $fetch
kill $loop
cat $FILE

