#!/bin/bash

# start spinner in background
spinner=(⡀ ⡄ ⡔ ⡜ ⠝ ⠛ ⠫ ⢣ ⢢ ⢠ ⢀ "⠀" "⠀" "⠀")
while true; do for c in "${spinner[@]}"; do echo "📦 $c" && sleep 0.1; done; done &
loop=$!

# only show if updates > 0
aur="$(paru -Qum --devel 2>/dev/null | wc -l)"
pacman="$(checkupdates 2>/dev/null | wc -l)"
updates=$(( aur + pacman ))
kill $loop
echo
(( updates > 0 )) && echo "📦 $updates"

