#!/bin/bash
#                  _ 
#  _ __  _ __ ___ (_)
# | '_ \| '__/ _ \| |
# | |_) | | | (_) | |
# | .__/|_|  \___// |
# |_|           |__/ 
##

set -e

dir=$(printf "java\nrust\npy\nsql" | dmenu)
dir="dox/${dir}_stuff"
project="$(find "$dir" -type d | dmenu)"
# tabbed -r 2 -c alacritty --embed '' -e nvim "$project"
tabbed -r 2 -c alacritty --embed '' -e zsh -c cd "$project"

