#!/bin/bash
#                                  _
#  _ __ ___ ___ _ __ ___  __ _  __| |
# | '__/ __/ __| '__/ _ \/ _` |/ _` |
# | |  \__ \__ \ | |  __/ (_| | (_| |
# |_|  |___/___/_|  \___|\__,_|\__,_|
#
##

sfeed_update
url=$(sfeed_plain "$HOME"/.sfeed/feeds/* | dmenu -l 33 -i -z 1000 |\
    sed -n 's@^.* \([a-zA-Z]*://\)\(.*\)$@\1\2@p')
test -n "$url" && $BROWSER "$url"

