#!/bin/bash
#  _
# | |_ _ __ ___   ___ _ __  _   _
# | __| '_ ` _ \ / _ \ '_ \| | | |
# | |_| | | | | |  __/ | | | |_| |
#  \__|_| |_| |_|\___|_| |_|\__,_|
#
##
# - handles torrents for tranmission-daemon with dmenu
##

function notif {
    toastify send --id 99 -t 5000 tmenu "$1"
}

function show_torrents() {
    for i in "${ids[@]}"; do
        info=$(transmission-remote -t "$i" -i)
        read -r _ name<<<"$(grep "Name:" <<<"$info")"
        read -r _ dled dus<<<"$(grep "Downloaded:" <<<"$info")"
        read -r _ _ size su _ _<<<"$(grep "Total size:" <<<"$info")"
        read -r _ time tu _ _<<<"$(grep "ETA" <<<"$info")"
        echo " $i  $dled$dus/$size$su  $time${tu:0:1}  $name"
    done
}

CHECK_ON=🔥
CHECK_OFF=😴

function show_files() {
    echo "     manage torrent"
    while read -r f; do
        read -r ID Done _ Selected Size Su Path <<<"$f"
        [ "$Selected" = "Yes" ] && checkbox=$CHECK_ON || checkbox=$CHECK_OFF
        printf "$checkbox %-3s %4s %-3s %s\n" "$ID" "$Done" "$Size$Su" "${Path#*/}"
    done <<< "$(transmission-remote -t "$sel" -f | tail -n+3)"
}


function tsm {
    transmission-remote -t "$sel" "$@" >/dev/null
}

MENU=dmenu; tty -s && MENU=fzf
function menu {
    if [ "$MENU" = fzf ]; then
        fzf --print-query --height 10 --prompt "$1 " | xargs echo
    else
        dmenu -i -z 1000 -p "$1"
    fi
}

function handle_action {
    action=$(printf "▶ start\n⏸ stop\n✖ remove\n☠ remove and delete" | menu "$name: ")
    [ -z "$action" ] && return

    case $action in
        *start)               tsm -s   && notif "$name started!";;
        *stop)                tsm -S   && notif "$name stopped!";;
        *remove)              tsm -r   && notif "$name removed!";;
        *"remove and delete") tsm -rad && notif "$name deleted!";;
    esac
}

while true; do
    read -ra ids<<<"$(transmission-remote -l | tail -n+2 | head -n-1 | awk '{print $1}' | tr '\n' ' ')"
    [ -z "${ids[*]}" ] && notif "no torrents!" && exit 1

    read -r _ sel _ _ _ _ _ name<<<"$(show_torrents | menu "torrents:")"
    [ -z "$sel" ] && exit

    while true; do
        read -r state ID _ _ _ <<< "$(show_files | menu "toggle file:")"
        [ -z "$state" ] && break

        [[ "$ID" = *"manage"* ]] && handle_action && break
        { [ "$state" = $CHECK_ON ] && tsm -G "$ID"; } || tsm -g "$ID"
    done
done

