#!/bin/bash
#  _
# | |_ ___  _ __ _ __
# | __/ _ \| '__| '__|
# | || (_) | |  | |
#  \__\___/|_|  |_|
#
##
# - search tpb for torrents using jq and dmenu
##

term=${1:-$(echo -n | dmenu -z 500 -p "search for torrents:")}
[ -z "$term" ] && exit 1

function show_torrents {
    # get torrents, sorted by seeds
    api_url="https://apibay.org/q.php"
    data="$(curl -s --data-urlencode "q=$term" "$api_url" --compressed | sed 's/`//g')"
    [ -z "$data" ] && toastify send torr "no curl data!" && return 1

    filter='sort_by(.seeders | tonumber) | reverse | map([.size,.seeders,.info_hash,.name] | join(" ")) | join("\n")'
    while read -r size seeds mhash name; do
        if (( size > 10*1024**3 - 1)); then # 10G
            icon="⣿"
        elif (( size > 5*1024**3 - 1)); then # 5G
            icon="⣷"
        elif (( size > 1024**3 - 1)); then # 1GB
            icon="⣧"
        elif (( size > 500*1024**2 - 1)); then # 500MB
            icon="⣇"
        elif (( size > 100*1024**2 - 1)); then # 100MB
            icon="⡇"
        elif (( size > 50*1024**2 - 1 )); then # 50MB
            icon="⡆"
        elif (( size > 10*1024**2 - 1 )); then # 10MB
            icon="⡄"
        else
            icon="⡀"
        fi
        printf "$icon %4s  🌱 $seeds    %-100s %s\n" "$(numfmt --to iec "$size")" "$name" "$mhash"
    done <<< "$(echo "$data" | jq -r "$filter")"
}

# get torrents and display menu
mhash="$(show_torrents | dmenu -i -z 1000 -l 20 -p "select a torrent to download:" | rev | cut -d' ' -f1 | rev)"
[ -n "$mhash" ] && handlr open "magnet:?xt=urn:btih:$mhash&dn=$term&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2F47.ip-51-68-199.eu%3A6969%2Fannounce"

