#!/bin/sh
#  _
# | |_ ___  _ __ _ __
# | __/ _ \| '__| '__|
# | || (_) | |  | |
#  \__\___/|_|  |_|
#
##
# - search tpb for torrents using jq and dmenu/fzf
##

# default to dmenu, if in terminal use fzf
MENU=dmenu; tty -s && MENU=fzf
LINES=${LINES:-10}

menu() {
    [ -z "$1" ] && echo "Usage: menu PROMPT" && exit 1
    if [ $MENU = fzf ]; then
        fzf --print-query --height $LINES --prompt "$1 "
    else
        dmenu -l $LINES -z 800 -p "$1"
    fi
}

mem_icon() {
    MB=$((1024*1024))
    GB=$((1024*MB))
    [ "$size" -gt $(( 10*GB - 1)) ] && echo "⣿" && return
    [ "$size" -gt $((  5*GB - 1)) ] && echo "⣷" && return
    [ "$size" -gt $((  1*GB - 1)) ] && echo "⣧" && return
    [ "$size" -gt $((500*MB - 1)) ] && echo "⣇" && return
    [ "$size" -gt $((100*MB - 1)) ] && echo "⡇" && return
    [ "$size" -gt $(( 50*MB - 1)) ] && echo "⡆" && return
    [ "$size" -gt $(( 10*MB - 1)) ] && echo "⡄" && return
    echo "⡀"
}

show_torrents() {
    # get torrents, sorted by seeds
    data="$(curl -s --data-urlencode "q=$term" "https://apibay.org/q.php" --compressed | sed 's/`//g')"
    [ -z "$data" ] && toastify send torr "no curl data!" && return 1

     echo "$data" | \
     jq -r 'sort_by(.seeders | tonumber) | reverse | map([.size,.seeders,.info_hash,.name] | join(" ")) | join("\n")' | \
    while read -r size seeds mhash name; do
        printf "$(mem_icon "$size") %4s  🌱 $seeds  🧲 %-100s %s\n" "$(numfmt --to iec "$size")" "$name" "$mhash"
    done
}

urlenc() {
    python -Ic "import urllib.parse as _; print(_.quote(input()))"
}

while true; do
    term=${1:-$(printf "" | menu "search for torrents:")}
    [ -n "$1" ] && shift
    [ -z "$term" ] && exit

    # get torrents and display menu
    selected="$(show_torrents | menu "select a torrent to download:" | tail -n1)"
    [ -z "$selected" ] && continue

    # extract selected and open
    mhash="$(echo "$selected" | rev | cut -d' ' -f1 | rev)"
    name="$(echo "$selected" | cut -d' ' -f9- | rev | cut -d' ' -f2- | rev | urlenc)"
    [ -n "$mhash" ] && xdg-open "magnet:?xt=urn:btih:$mhash&dn=$name&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2F47.ip-51-68-199.eu%3A6969%2Fannounce"
done

