#!/bin/bash
##            _                           _   _
# __   _____ | |_   _ _ __ ___   ___  ___| |_| |
# \ \ / / _ \| | | | | '_ ` _ \ / _ \/ __| __| |
#  \ V / (_) | | |_| | | | | | |  __/ (__| |_| |
#   \_/ \___/|_|\__,_|_| |_| |_|\___|\___|\__|_|
#
##
# - controls volume with pulsemixer and sends a notification
##

# generate id for notification
[ ! -f /tmp/volctlnotid ] && shuf -i 0-9999 -n 1 > /tmp/volctlnotid
ID=$(cat /tmp/volctlnotid)

# update notif
function notif {
    toastify send -t 5000 -i multimedia-volume-control --id "$ID" volumectl "$1"
}

case "$1" in
    "togmute")
        pulsemixer --toggle-mute
        (($(pulsemixer --get-mute))) && notif "muted" && exit 0 ;;
    "up") pulsemixer --change-volume +5 ;;
    "down") pulsemixer --change-volume -5 ;;
    "next") pulseaudio-control next-sink ;;
esac

# show volume level
volume="$(pulsemixer --get-volume | awk '{print $1}')"
notif "$volume%"

