#!/bin/bash
##            _                           _   _ 
# __   _____ | |_   _ _ __ ___   ___  ___| |_| |
# \ \ / / _ \| | | | | '_ ` _ \ / _ \/ __| __| |
#  \ V / (_) | | |_| | | | | | |  __/ (__| |_| |
#   \_/ \___/|_|\__,_|_| |_| |_|\___|\___|\__|_|
#                                                     
##

case "$1" in
    "up") pulsemixer --change-volume +5 ;;
    "down") pulsemixer --change-volume -5 ;;
esac

# notify-send "volume $(pulsemixer --get-volume | awk '{print $1}')"

