#!/bin/bash
##            _                           _   _
# __   _____ | |_   _ _ __ ___   ___  ___| |_| |
# \ \ / / _ \| | | | | '_ ` _ \ / _ \/ __| __| |
#  \ V / (_) | | |_| | | | | | |  __/ (__| |_| |
#   \_/ \___/|_|\__,_|_| |_| |_|\___|\___|\__|_|
#
##
# - controls volume with pulsemixer and sends a notification
##

# update notif
function notif {
    toastify send -t 5000 --id 3027 "$@"
}

case "$1" in
    "togmute")
        pulsemixer --toggle-mute
        (($(pulsemixer --get-mute))) && notif -i audio-volume-muted volumectl muted && exit 0 ;;
    "up") pulsemixer --change-volume +5 ;;
    "down") pulsemixer --change-volume -5 ;;
    "next") pulseaudio-control next-sink ;;
esac

# show volume level
volume="$(pulsemixer --get-volume | awk '{print $1}')"
notif -i multimedia-volume-control volumectl "$volume%"

