#!/usr/bin/bash

alias l="lsd --group-dirs first"
alias ls="l -al"
alias la="l -a"
alias ll="l -l"
alias lt="lsd --tree"

alias cat="bat"
alias du="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
alias mkd="mkdir -pv"
alias ping="prettyping --nolegend"
alias unp="unp -U"
alias yt="youtube-dl --add-metadata -ic"
alias yta="youtube-dl --add-metadata -xic"

alias snap="sudo snap"
alias top="sudo htop"

alias dotfiles="git --git-dir=\$HOME/dotfiles --work-tree=\$HOME"
alias refr="source ~/.config/zsh/.zshrc"

alias btsport1='acestream-launcher -p vlc acestream://fa6a2e693b70e230276843043b5d0fb8b8e42998'
