#!/usr/bin/bash

alias l="lsd --group-dirs first --date relative --size short"
alias la="l -A"
alias ll="l -l"
alias ls="l -Al"
alias lt="l --tree"

alias s="sudo systemctl"
alias cat="bat -p"
alias du="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
alias mkd="mkdir -pv"
alias ping="prettyping --nolegend"
alias unp="unp -vU"
alias yt="youtube-dl --add-metadata -ic"
alias yta="youtube-dl --add-metadata -xic"
alias tsm="transmission-remote"
alias top="sudo htop"
alias tmon="watch -d -n 1 transmission-remote -l"
alias who="grc who -a"

alias dotfiles="git --git-dir=\$HOME/dotfiles --work-tree=\$HOME"
alias refr="source ~/.config/zsh/.zshrc"
alias todo="grep -nrEe 'TODO|FIXME' ."
alias npm="npm --prefix=\$HOME/.config/npm"

