#!/usr/bin/env bash

export insidecolor=00000000
export ringcolor=3b425200
export keyhlcolor=5e81acff
export bshlcolor=bf616aff
export separatorcolor=00000000
export insidevercolor=00000000
export insidewrongcolor=00000000
export ringvercolor=a3be8cff
export ringwrongcolor=bf616aff
export verifcolor=ffffffff
export timecolor=eceff4ff
export datecolor=e5e9f0ff
export loginbox=2e344033
export font="Blex Mono Nerd Font"
export locktext="jay@mothership"
export lock_timeout=5

