assume_yes = true
disable = ["node"]
ignore_failures = ["git_repos"]
#only = ["system", "emacs"]
#no_retry = true
#run_in_tmux = true
remote_topgrades = ["jaytauron.xyz"]
ssh_arguments = "-o ConnectTimeout=2"
remote_topgrade_path = ".bin/topgrade"
#tmux_arguments = "-S /var/tmux.sock"
set_title = true
cleanup = true

[git]
max_concurrency = 5
repos = [
    "~/repos/*/",
]
#predefined_repos = false
arguments = "--rebase --autostash"

[composer]
self_update = true

[pre_commands]
# "System update" = "paru -Syu --devel"

[commands]

[linux]
yay_arguments = "--devel"
#enable_tlmgr = true
#emerge_sync_flags = "-q"
#emerge_update_flags = "-uDNa --with-bdeps=y world"

