#!/bin/bash

###
# BSPC
bspc config border_width 0
bspc config window_gap 10
bspc config top_padding 0
bspc config bottom_padding 33
bspc config left_padding 0
bspc config right_padding 0

# Multihead behavior
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config split_ratio             0.48
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config automatic_scheme        spiral
bspc config pointer_follows_focus   false
bspc config removal_adjustment      true
bspc config pointer_modifier        mod1
bspc config pointer_action1         move
bspc config pointer_action2         resize_corner

###
# BSPC RULES
bspc rule -a Zathura state=tiled
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a ckb-next state=floating
bspc rule -a "ProtonMail Bridge" state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Discover-overlay state=floating
bspc rule -a "Manjaro Settings Manager" state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Java state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Font-manager state=floating
bspc rule -a BAPERS state=floating
bspc rule -a Xfce4-power-manager-settings state=floating
bspc rule -a Element-Nightly state=floating
bspc rule -a Seahorse state=floating

bspc rule -a lightcord desktop=^3
bspc rule -a mpv desktop=^7
bspc rule -a Brave-browser desktop=^6
bspc rule -a "JetBrains Toolbox" manage=on monitor=^1

###
# MONITORS
monitors="$(xrandr -q | grep connected | cut -f1 -d" ")"
n_monitors="$(wc -l <<< "$monitors")"
main=$(grep eDP <<< "$monitors")

if (( n_monitors == 2 )); then
    hdmi=$(grep HDMI <<< "$monitors")
    xrandr --output "$hdmi" --auto --above "$main"
    bspc monitor "$main" -d I II III IV V
    bspc monitor "$hdmi" -d VI VII VIII IX X
    bspc monitor "$main" -s "$hdmi"
else
    xrandr --auto
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

###
# init programs
function run { pgrep -x "${1::15}" ||eval "$@" & }
# set cursor straight away
run xsetroot -cursor_name left_ptr
# first startup programs
run dmenu_path
run protonmail-bridge --no-window
run ckb-next -b
# visual
run nitrogen --restore
run picom -bc --experimental-backends
/home/jay/.config/polybar/launch.sh
# daemons, settings etc
run optimus-manager-qt
run blueman-tray
run light-locker
run sxhkd
# run offlineimap
run lxpolkit
run xbanish
run bluetooth off
run wifi off
run numlockx on
run playerctld daemon
run spotifyd
run cleanfullscreen
# non essential startup stuff
run lightcord --start-minimized
run discord-rpc-extension
run element-desktop-nightly --hidden
run run_keybase -a

# focus 2nd desktop and open terminal
bspc desktop -f II
run tabbed -kc -r 2 alacritty --embed WID

