#! /bin/sh

###
# MONITORS
#

xrandr --output HDMI1 --auto --above eDP1

n_monitors=$(xrandr --listactivemonitors | awk '/Monitors/ {print $2}')
if [ "$n_monitors" = "2" ]; then
    bspc monitor HDMI1 -d 6 7 8 9 10
    bspc monitor eDP1  -d 1 2 3 4 5
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

###
# BSPC
#  
bspc config border_width         0
bspc config window_gap          20

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config automatic_scheme     spiral
bspc config pointer_follows_focus true
bspc config pointer_modifier control

bspc rule -a mplayer2 state=floating
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a ckb-next state=floating
bspc rule -a caja state=floating

###
# INIT programs
#
sxhkd &
/home/jay/.config/polybar/launch.sh &
ulauncher --hide-window &
compton -b &
feh --auto-reload --bg-scale /home/jay/pix/current_wall.jpg &
ckb-next -b &

