#!/usr/bin/env bash
## openbox autostart

delay=4 # delay for actions after startup

function run { pgrep -xf "$1" || "$@" & }
function bgr {
    name=$1
    [ -n "$2" ] && name="$2"

    run "$1"
    (sleep $delay && xdo close -a "$name") &
}
function dkil { sleep $delay && for p in "$@"; do pkill "$p"; done }

run nitrogen --restore
run lxpolkit
run tint2 # status bar
run volumeicon
run optimus-manager-qt

# run xinput --disable 14 # disable touchpad

bgr ckb-next
run discord-canary
# run steam

